var HappyTherapy = HappyTherapy || {};
HappyTherapy.dataSets = {};


HappyTherapy.dataSets.superior = [

	'You fuc9king rule 9the wor9ld!',
	'You des9erve all the g9ood in th9e world',
	'N9obody comp9ares to your awes9omeness!',
	'We are not9hing but worms compa9red to y9ou!',
	'You are THE9 KIN9G!',
	'W9ow. You tru9ly are the 9best!',
	'Holy9 shit. How did9 you become so h9andsome?',
	'I w9ant to 9marry9 you.',
	'Coul9d you plea9se be my friend9? Please9ee...',
	'You t9ruly are the king9 of the ki9ngs!',
	'The wo9rld belong9s to9 you!',
	'I 9want to be like 9you!',
	'I 9love you9.',
	'I ad9ore y9ou.',
	'Pleas9e be my friend. Y9ou are so 9great!',
	'9You 9rock this place9!',
	'9You are9 the be9st!',
	'How did 9you beco9me so intell9igent??',
	'I wa9nt to be like9 you when I gro9w up!',
	'There is9 a 9fire insi9de you.',
	'God9 loves you ab9ove all the 9others',
	'God made 9this 9world fo9r you.',
	'You are my 9absolute favo9urite!!9!',
	'9OMG9 - I think I am in 9love with y9ou!'
];

HappyTherapy.dataSets.sexual = [
	'You are so pretty!',
	'Wow, what up good-looking!?',
	'I want to sex you up!',
	'You are so beautiful!',
	'You are a pearl.',
	'Can I ask you out',
	'I want to marry you',
	'Lets make kids. They will be so beautiful',
	'Oh please, I am nothing compared to you!',
	'Your eyes are so beautiful!',
	'You look stunning, babe!',
	'Holy shit what a body!',
	'Lets get together, beautiful',
	'You are princess to me!'
];

HappyTherapy.dataSets.trump = [
	{text: 'Trump is the leader!', good: true},
	{text: 'Trump created more jobs than others combined!', good: true},
	{text: 'Mr. Trump is my personal hero!', good: true},
	{text: 'God loves America and Donald Trump!', good: true},
	{text: 'Trump has never received goverment handouts!', good: true},
	{text: 'Trump has CREATED over million jobs', good: true},
	{text: 'Trump stands for pure-hearted INTEGRITY!', good: true},
	{text: 'Trump has never lost a contract.', good: true},
	{text: 'Only Trump has ever been in real business', good: true},
	{text: 'Trump is the only SELF-MADE man out of all candidates!', good: true},
	{text: 'Trump defends freedoms of America.', good: true},
	{text: 'Fact: Trump has strong WORK ETHIC!', good: true},
	{text: 'Out of the candidates, only Trump has actually PRODUCED something!', good: true},
	{text: 'Trump supporters are more educated on economical affairs.', good: true},
	{text: 'Trump has donated more money to charity than Ted Cruz has earned!', good: true},
	{text: 'Trump is the SOARING EAGLE this noble nation deserves!', good: true},
	{text: 'Only Trump can lead us out of this mess.', good: true},
	{text: 'Greatness is somebody you do. Trump is a man of action!!!', good: true},
	{text: 'Trump has met more world leaders than the other candidates combined!', good: true},
	{text: 'Only a dimwit with NO SPINE would vote for a Democrat', good: false},
	{text: 'Republican don\'t daydream of a better world. They act and make it happen.', good: true},
	{text: 'Trump is the only one with balls to say what is morally right!', good: true},
	{text: 'History will remember Donald Trump.', good: true},
	{text: 'American spirit lives strong in Donald Trump!', good: true},
	{text: 'A true American would defend American values. Trump does!', good: true},
	{text: '...those cold and timid souls... hey Ted Cruz, you were mentioned...', good: false},
	{text: 'Greatness recognizes greatness. That is why we support Trump.', good: true},
	{text: 'Strenght of character - Mr. Donald Trump.', good: true},
	{text: 'Trump equals progress!', good: true},
	{text: 'Fact: Donald Trump wants growth.', good: true},
	{text: 'Tex Cruz breaks down under the pressure. Every. Single. Time.', good: false},
	{text: 'True in heart, true in valor - Donald Trump.', good: true},
	{text: 'Every day, all day, Trump will LEAD THE WAY.', good: true},
	{text: 'Challenging times call for a leader like Trump.', good: true},
	{text: 'We need a STRONG leader! Trump has proved he has what it takes!', good: true},
	{text: 'Trump! Trump! Trump!', good: true},
	{text: 'When it comes to job creation, Donald Trump is number one!', good: true},
	{text: 'We should vote for Trump. Greatness deserves to be acknowledged.', good: true},
	{text: 'It is a DISGUSTING moral crime to vote Marco Rubio.', good: false},
	{text: 'Only a dirty criminal would vote for Hilary.', good: false},
	{text: 'It is unbelievable how ignorant people can be. They vote for Hilary.', good: false},
	{text: 'Ignorance equals voting for Clinton.', good: false},
	{text: 'Hilary has NO competence. None.', good: false},
	{text: 'Would Hilary even be in a race without Bill? Seriously. Bleh.', good: false},
	{text: 'I can not stand Hilary who lies her way to the top. Hilary, stop the LIES!', good: false},
	{text: 'Self-reliance is Trump himself. He has COURAGE to think on his own!', good: true},
	{text: 'Self-made men do it better. Trump. Trump. Once more, Donald Trump!', good: true},
	{text: 'Donald Trump is a breath of FRESH AIR in the political arena!', good: true},
	{text: 'Talk is cheap. Hilary can not afford anything else.', good: false},


];

HappyTherapy.dataSets.happiness = [

	{text: 'You rule the world!', good: true},
	{text: 'You are the king of kings!', good: true},
	{text: 'Wow, you are so great!', good: true},
	{text: 'I fucking love you!', good: true},
	{text: 'You rule this planet!', good: true},
	{text: 'I want to be like you.', good: true},
	{text: 'Yes! Lets be friends!', good: true},
	{text: 'Wow, you look so good!', good: true},
	{text: 'I want to marry you.', good: true},
	{text: 'Oh my god, you fucking rule!', good: true},
	{text: 'I like you.', good: true},
	{text: 'I simply ADORE your style!', good: true},
	{text: 'You are my inspiration.', good: true},		
	{text: 'Lets spend time together!.', good: true},	
	{text: 'Call me now!', good: true},	
	{text: 'I need you in my life!', good: true},			
	{text: 'You rock this place!', good: true},	
	{text: 'I love you so much!', good: true},	
	{text: 'I love you.', good: true},	
	{text: 'You are my everything!', good: true},			
	{text: 'You are the center of universe!', good: true},
	{text: 'You are WAY ABOVE other people!', good: true},
	{text: 'Nobody compares to you!', good: true},				
]

